
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smiket
 */
public class Arrived extends javax.swing.JFrame {
int k=0,l=Integer.parseInt(Book1.time);

Timer t =null;
public void dis()
{
    this.dispose();
}
    /**
     * Creates new form Arrived
     */
    public Arrived() {
        initComponents();
       
         driver dr = new driver();
        dr.name =Book1.namedriver;
        dr.rat = Book1.rot;
        dr.vi = Book1.vid;
        dr.mob =Book1.mob;
        
        name.setText(dr.name);
        ra.setText(dr.rat);
        vi.setText(dr.vi);
        mn.setText(dr.mob);
        this.setLocationRelativeTo(null);
        Arrivedpanel.setBackground(new Color(0,0,0,240));
         min.setText(1+"");
         dest.setText(Book1.dp+" in");
       
        t = new Timer(1000,new ActionListener(){
                @Override
              
                public void actionPerformed(ActionEvent e) {
                   
                 if(k==0){
                     lt.setText(k+"0");
                     l--;
                     k=59;
                 
                 } 
                 
                 else if(l==-1){
                     
                     t.stop();
                     t =null;
                     new Travelling().setVisible(true); 
                     dis();
                 
                 }
                 else{
                     min.setText(l+"");
                     if(k<10)
                     lt.setText("0"+k);
                     else lt.setText(""+k);
                     k--;
                 
                 }
                }
            
            
            });
            t.start();
           

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Arrivedpanel = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lt = new javax.swing.JLabel();
        dest = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        min2 = new javax.swing.JLabel();
        min3 = new javax.swing.JLabel();
        min4 = new javax.swing.JLabel();
        min5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        vi = new javax.swing.JLabel();
        mn = new javax.swing.JLabel();
        ra = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(978, 649));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Arrivedpanel.setBackground(new java.awt.Color(0, 0, 0));

        min.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setText("0");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(":");

        lt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lt.setForeground(new java.awt.Color(255, 255, 255));
        lt.setText("00");

        dest.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dest.setForeground(new java.awt.Color(255, 255, 255));
        dest.setText("dest");

        min1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        min1.setForeground(new java.awt.Color(255, 255, 255));
        min1.setText("Driver Details");

        min2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        min2.setForeground(new java.awt.Color(255, 255, 255));
        min2.setText("Mobile No:");

        min3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        min3.setForeground(new java.awt.Color(255, 255, 255));
        min3.setText("Name:");

        min4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        min4.setForeground(new java.awt.Color(255, 255, 255));
        min4.setText("Vehicle Id:");

        min5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        min5.setForeground(new java.awt.Color(255, 255, 255));
        min5.setText("Rating:");
        min5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min5MouseClicked(evt);
            }
        });

        name.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("N");

        vi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vi.setForeground(new java.awt.Color(255, 255, 255));
        vi.setText("N");

        mn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mn.setForeground(new java.awt.Color(255, 255, 255));
        mn.setText("N");

        ra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ra.setForeground(new java.awt.Color(255, 255, 255));
        ra.setText("N");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("You will be arriving ");

        javax.swing.GroupLayout ArrivedpanelLayout = new javax.swing.GroupLayout(Arrivedpanel);
        Arrivedpanel.setLayout(ArrivedpanelLayout);
        ArrivedpanelLayout.setHorizontalGroup(
            ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArrivedpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArrivedpanelLayout.createSequentialGroup()
                        .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(min2)
                            .addComponent(min5))
                        .addGap(18, 18, 18)
                        .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ArrivedpanelLayout.createSequentialGroup()
                                .addComponent(ra)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ArrivedpanelLayout.createSequentialGroup()
                                .addComponent(mn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(min)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dest)
                                    .addGroup(ArrivedpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lt)))
                                .addGap(98, 98, 98))))
                    .addGroup(ArrivedpanelLayout.createSequentialGroup()
                        .addComponent(min3)
                        .addGap(53, 53, 53)
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(17, 17, 17))
                    .addGroup(ArrivedpanelLayout.createSequentialGroup()
                        .addComponent(min4)
                        .addGap(18, 18, 18)
                        .addComponent(vi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ArrivedpanelLayout.createSequentialGroup()
                        .addComponent(min1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        ArrivedpanelLayout.setVerticalGroup(
            ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArrivedpanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(min1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ArrivedpanelLayout.createSequentialGroup()
                        .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(min3)
                            .addComponent(name))
                        .addGap(29, 29, 29)
                        .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(min4)
                            .addComponent(vi))
                        .addGap(26, 26, 26))
                    .addGroup(ArrivedpanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dest)
                        .addGap(18, 18, 18)))
                .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min2)
                    .addComponent(mn)
                    .addComponent(min)
                    .addComponent(jLabel3)
                    .addComponent(lt))
                .addGap(26, 26, 26)
                .addGroup(ArrivedpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ra)
                    .addComponent(min5))
                .addGap(106, 106, 106))
        );

        getContentPane().add(Arrivedpanel);
        Arrivedpanel.setBounds(170, 120, 620, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void min5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min5MouseClicked
t.stop();
                     t =null;
                     new Travelling().setVisible(true); 
                     dis();      
    }//GEN-LAST:event_min5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arrived.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arrived.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arrived.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arrived.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arrived().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arrivedpanel;
    private javax.swing.JLabel dest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lt;
    private javax.swing.JLabel min;
    private javax.swing.JLabel min1;
    private javax.swing.JLabel min2;
    private javax.swing.JLabel min3;
    private javax.swing.JLabel min4;
    private javax.swing.JLabel min5;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel name;
    private javax.swing.JLabel ra;
    private javax.swing.JLabel vi;
    // End of variables declaration//GEN-END:variables
}
