
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smiket
 */
public class Login extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement st=null;
    PreparedStatement pst=null;
     PreparedStatement pstt=null;
    static  String y;
    static String user;
    static String fname;

    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        loginpanel.setBackground(new Color(0,0,0,239));
        y= useridlog.getText();
        
    }
    public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    public  void Updater(String user){
        
         String query="UPDATE `user_info` SET `loggedin`='0' WHERE Username=?";
        try {
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data", "root","");
             pst=conn.prepareStatement(query);
             pst.setString(1,user);
            pst.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Updater Not Working");
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formclose = new javax.swing.JLabel();
        formminimize = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        loginpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        useridlog = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passlog = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 240, 239));
        jLabel1.setText("Login");

        formclose.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        formclose.setForeground(new java.awt.Color(235, 9, 9));
        formclose.setText("X");
        formclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formcloseMouseClicked(evt);
            }
        });

        formminimize.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        formminimize.setForeground(new java.awt.Color(6, 110, 207));
        formminimize.setText("-");
        formminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formminimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(formminimize)
                .addGap(18, 18, 18)
                .addComponent(formclose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formclose)
                            .addComponent(formminimize)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(978, 649));
        setUndecorated(true);
        getContentPane().setLayout(null);

        loginpanel.setBackground(new java.awt.Color(0, 0, 0));
        loginpanel.setForeground(new java.awt.Color(240, 240, 240));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Username:");

        useridlog.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        useridlog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                useridlogKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("LOGIN");

        passlog.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        passlog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passlogKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(224, 87, 7));
        jLabel12.setText("X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(166, 162, 162));
        jLabel13.setText("-");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(148, 146, 139));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Register here");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(224, 28, 7));
        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(32, 111, 230));
        jButton2.setText("Login");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passlog, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(useridlog))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                .addGap(0, 130, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        loginpanelLayout.setVerticalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(useridlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(passlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(40, 40, 40))
        );

        getContentPane().add(loginpanel);
        loginpanel.setBounds(280, 130, 460, 320);

        jLabel2.setBackground(new java.awt.Color(40, 40, 240));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (2).jpg"))); // NOI18N
        jLabel2.setText("ihudsagfiudgfiusdg");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 980, 653);

        setSize(new java.awt.Dimension(979, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formcloseMouseClicked
     
        System.exit(0);
    }//GEN-LAST:event_formcloseMouseClicked

    private void formminimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formminimizeMouseClicked
      this.setState(JFrame.ICONIFIED); //eg4rerg
    }//GEN-LAST:event_formminimizeMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
          Updater(useridlog.getText());
                   System.exit(0);
               
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.setState(JFrame.ICONIFIED);      
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
        new Registration().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            
         Updater(useridlog.getText());
                   System.exit(0);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void passlogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passlogKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER)
    {
               String x=String.valueOf(passlog.getPassword());
       y=useridlog.getText();
       int w=0,q=0;
       if(y.equals(""))
       {
           JOptionPane.showMessageDialog(null,"Enter Username");
       }
      else if(x.equals(""))
       {
          JOptionPane.showMessageDialog(null,"Please enter Password");
       }
       else
      {
          w++;
      }
       if(w==1)
       {
           String pass;
           String log;
        try{
            String query="SELECT `Password`, `loggedin`,`First Name` FROM `user_info` WHERE Username=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data", "root","");
            st=conn.prepareStatement(query);
            st.setString(1, useridlog.getText());
           
            ResultSet rst =st.executeQuery();
            while(rst.next())
            {
                q++;
                pass=rst.getString("Password");
                log=rst.getString("loggedin");
                fname=rst.getString("First Name");
                if(log.equals("1"))
                {
                    JOptionPane.showMessageDialog(null,"Already Logged in");
                }              
                else if(pass.equals(x))
                { 
                   
                JOptionPane.showMessageDialog(null,"Login Successful");
                String que="UPDATE `user_info` SET `loggedin`='1' WHERE Username=?";
                        pst=conn.prepareStatement(que);
                        pst.setString(1,y);
                        pst.executeUpdate();
                this.dispose();
               Proifile1 pf=new Proifile1();
        pf.pack();
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
                
                }
            else
            {
              JOptionPane.showMessageDialog(null,"Password Incorrect");
              
            }
            }
            if(q==0)
            while(!rst.next())
            {
                JOptionPane.showMessageDialog(null,"User not found");
                break;
            }
        
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(null,"Login Failed");
                    }

    }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_passlogKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
                            String x=String.valueOf(passlog.getPassword());
       y=useridlog.getText();
       int w=0,q=0;
       if(y.equals(""))
       {
           JOptionPane.showMessageDialog(null,"Enter Username");
       }
      else if(x.equals(""))
       {
          JOptionPane.showMessageDialog(null,"Please enter Password");
       }
       else
      {
          w++;
      }
       if(w==1)
       {
           String pass;
        try{
            String query="SELECT `Password` FROM `user_info` WHERE Username=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data", "root","");
            st=conn.prepareStatement(query);
            st.setString(1, useridlog.getText());
            ResultSet rst =st.executeQuery();
            while(rst.next())
            {
                q++;
                pass=rst.getString("Password");
                if(pass.equals(x))
                { 
                   
                JOptionPane.showMessageDialog(null,"Login Successful");
                 String quey="UPDATE `user_info` SET `loggedin`='0' WHERE Username=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data", "root","");
            pstt=conn.prepareStatement(quey);
            pstt.setString(1, y);
                this.dispose();
               Proifile1 pf=new Proifile1();
        pf.pack();
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
                
                }
            else
            {
              JOptionPane.showMessageDialog(null,"Password Incorrect");
              
            }
            }
            if(q==0)
            while(!rst.next())
            {
                JOptionPane.showMessageDialog(null,"User not found");
                break;
            }
        
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(null,"Login Failed");
                    }

    }
      
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void useridlogKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridlogKeyPressed
  if(evt.getKeyCode()==KeyEvent.VK_ENTER)
    {
               String x=String.valueOf(passlog.getPassword());
       y=useridlog.getText();
       int w=0,q=0;
       if(y.equals(""))
       {
           JOptionPane.showMessageDialog(null,"Enter Username");
       }
      else if(x.equals(""))
       {
          JOptionPane.showMessageDialog(null,"Please enter Password");
       }
       else
      {
          w++;
      }
       if(w==1)
       {
           String pass;
        try{
            String query="SELECT `Password` FROM `user_info` WHERE Username=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data", "root","");
            st=conn.prepareStatement(query);
            st.setString(1, useridlog.getText());
            
            ResultSet rst =st.executeQuery();
            while(rst.next())
            {
                q++;
                pass=rst.getString("Password");
                if(pass.equals(x))
                { 
                   
                JOptionPane.showMessageDialog(null,"Login Successful");
                 String quey="UPDATE `user_info` SET `loggedin`='0' WHERE Username=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data", "root","");
            pstt=conn.prepareStatement(quey);
            pstt.setString(1, y);
                this.dispose();
               Proifile1 pf=new Proifile1();
        pf.pack();
        pf.setVisible(true);
        pf.setLocationRelativeTo(null);
                
                }
            else
            {
              JOptionPane.showMessageDialog(null,"Password Incorrect");
              
            }
            }
            if(q==0)
            while(!rst.next())
            {
                JOptionPane.showMessageDialog(null,"User not found");
                break;
            }
        
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(null,"Login Failed");
                    }

    }
    }          // TODO add your handling code here:
    }//GEN-LAST:event_useridlogKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   Updater(useridlog.getText());
                   System.exit(0);
                   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formclose;
    private javax.swing.JLabel formminimize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JPasswordField passlog;
    public static javax.swing.JTextField useridlog;
    // End of variables declaration//GEN-END:variables
}
