
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import javafx.scene.input.KeyCode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smiket
 */
public class Travelling extends javax.swing.JFrame {

    /**
     * Creates new form traveling
     */
    public Travelling() {
        initComponents();
        this.setLocationRelativeTo(null);
        trapanel.setBackground(new Color(0,0,0,240));
//          
         try{
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/driver_data","root","");
         String qury="SELECT * FROM `driver_info` WHERE 1";
            PreparedStatement  stm = conn.prepareStatement(qury);
            ResultSet rs= stm.executeQuery();
            while(rs.next()){
                String av= rs.getString("Available");
                if((Integer.parseInt(av)==1)||Book1.namedriver.equals(rs.getString(1))){
                realloc(rs.getString(1));
                }
            
            }
         
         }catch(Exception ec){
         
         System.out.println("kya hua yaar");
         }
        
            String dis="";
            String dir="";
       
        try{
        Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/locations","root","");
         String query="SELECT `distance`, `direction` FROM `data` WHERE Location =?"; 
            PreparedStatement  st = cot.prepareStatement(query); 
            st.setString(1, Book1.dp);
            ResultSet rs = st.executeQuery();
           
            while(rs.next()){
               
                dis =rs.getString("distance");
                dir =rs.getString("direction");
            }
           
          
            
        }catch(SQLException ex){
         JOptionPane.showMessageDialog(null,"realloc nhi hua0");
        
        }
   
          try{
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/driver_data","root","");
         String qury="UPDATE `driver_info` SET `location`=?,`Available`='1',`dis`=?,`dir`=? WHERE Name = ?";
            
            PreparedStatement  stm = conn.prepareStatement(qury); 
            stm.setString(1, Book1.dp);
            stm.setString(2, dis);
            stm.setString(3, dir);
            stm.setString(4,Book1.namedriver);
            stm.executeUpdate();
          
            }catch(Exception ec)
            {
                  JOptionPane.showMessageDialog(null,"realloc nhi hua1");
                
            }
         
        
          
    }
    
    public void realloc(String drname){
        int ran =(int)((Math.random()*10)%10);
         String loc="" ;
            String dis="";
            String dir="";
       
        try{
        Connection cot = DriverManager.getConnection("jdbc:mysql://localhost:3306/locations","root","");
         String query="SELECT `Location`, `distance`, `direction` FROM `data` WHERE spl =?"; 
            PreparedStatement  st = cot.prepareStatement(query); 
            st.setInt(1, ran);
            ResultSet rs = st.executeQuery();
           
            while(rs.next()){
                loc =rs.getString("Location");
                dis =rs.getString("distance");
                dir =rs.getString("direction");
            }
           
          
            
        }catch(SQLException ex){
         JOptionPane.showMessageDialog(null,"realloc nhi hua0");
        
        }
         System.out.println(loc +">"+dis+">"+dir);
          try{
             Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/driver_data","root","");
         String qury="UPDATE `driver_info` SET `location`=?,`Available`='1',`dis`=?,`dir`=? WHERE Name = ?";
            
            PreparedStatement  stm = conn.prepareStatement(qury); 
            stm.setString(1, loc);
            stm.setString(2, dis);
            stm.setString(3, dir);
            stm.setString(4,drname);
            stm.executeUpdate();
          
            }catch(Exception ec)
            {
                  JOptionPane.showMessageDialog(null,"realloc nhi hua1");
                
            }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        trapanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rslide = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(978, 609));
        setUndecorated(true);
        getContentPane().setLayout(null);

        trapanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Destination Reached");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Rate Driver");

        rslide.setBackground(new java.awt.Color(0, 0, 0));
        rslide.setForeground(new java.awt.Color(255, 255, 255));
        rslide.setMajorTickSpacing(1);
        rslide.setMaximum(10);
        rslide.setPaintLabels(true);
        rslide.setPaintTicks(true);
        rslide.setValue(0);

        javax.swing.GroupLayout trapanelLayout = new javax.swing.GroupLayout(trapanel);
        trapanel.setLayout(trapanelLayout);
        trapanelLayout.setHorizontalGroup(
            trapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trapanelLayout.createSequentialGroup()
                .addGroup(trapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(trapanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(trapanelLayout.createSequentialGroup()
                        .addGroup(trapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(trapanelLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(trapanelLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(trapanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(rslide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        trapanelLayout.setVerticalGroup(
            trapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trapanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(rslide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(trapanel);
        trapanel.setBounds(293, 175, 412, 340);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (2).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int rate;
      
        rate = (Integer.parseInt(Book1.rot)*3 +rslide.getValue())/4;
        try{
        String query= "UPDATE `driver_info` SET `rating`=? WHERE Name =?";
        Connection cin = DriverManager.getConnection("jdbc:mysql://localhost:3306/driver_data","root","");
        PreparedStatement prt = cin.prepareStatement(query);
        prt.setString(1, Integer.toString(rate));
        prt.setString(2,Book1.namedriver );
        prt.executeUpdate();
//        System.out.print("yeh hai saach"+dr.rat+">>"+dr.name+">>"+rate);
        }catch(SQLException ec){
        JOptionPane.showMessageDialog(null, "Nahi hua rate");
        }
          System.out.print("yeh hai saach"+Book1.rot+">>"+Book1.namedriver+">>"+rate);
        this.dispose();
        new Proifile1().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
//       Proifile1 pr = new Proifile1();
//       pr.Updater(Login.y);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travelling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider rslide;
    private javax.swing.JPanel trapanel;
    // End of variables declaration//GEN-END:variables
}
