
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smiket
 */
public class Wallet1 extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement st=null;
    static String x;
    static int walbalfinal;
    String n=Login.y;

    /**
     * Creates new form Wallet1
     */
    public Wallet1() {
        initComponents();
        this.setLocationRelativeTo(null);
        walletpanel.setBackground(new Color(0,0,0,240));
           try{
         String query="SELECT`WalBal` FROM `user_info` WHERE Username=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data", "root","");
            st=conn.prepareStatement(query);
            st.setString(1,n);
             ResultSet rst =st.executeQuery();
            while(rst.next())
            {   String bal=rst.getString("WalBal");
                currbalance.setText(bal);
                this.dispose();
                }
            
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(null,"Error wallet");
        }
        
    }
            public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        walletpanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toadd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        currbalance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(978, 609));
        setUndecorated(true);
        getContentPane().setLayout(null);

        walletpanel.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(32, 111, 230));
        jButton2.setText("Add to Wallet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(242, 0, 0));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 240, 239));
        jLabel2.setText("Add Amount to be added:");

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 240, 239));
        jLabel3.setText("New Balance:");

        toadd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        toadd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                toaddKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 240, 239));
        jLabel4.setText("Current Balance:");

        currbalance.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        currbalance.setForeground(new java.awt.Color(237, 240, 239));
        currbalance.setText("0");
        currbalance.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                currbalancePropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 240, 239));
        jLabel6.setText("Wallet");

        balance.setBackground(new java.awt.Color(0, 0, 0));
        balance.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        balance.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout walletpanelLayout = new javax.swing.GroupLayout(walletpanel);
        walletpanel.setLayout(walletpanelLayout);
        walletpanelLayout.setHorizontalGroup(
            walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, walletpanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toadd, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(walletpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(currbalance)))
                .addGap(120, 120, 120))
            .addGroup(walletpanelLayout.createSequentialGroup()
                .addGroup(walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(walletpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(walletpanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        walletpanelLayout.setVerticalGroup(
            walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walletpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(walletpanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addGroup(walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(walletpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(walletpanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(currbalance)))
                .addGap(81, 81, 81))
        );

        getContentPane().add(walletpanel);
        walletpanel.setBounds(230, 90, 480, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Webp.net-resizeimage (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 653);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        x=currbalance.getText();
        String y=toadd.getText();
        if(y.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please add amount");
        }
        int a=Integer.parseInt(x);
        int b=Integer.parseInt(y);
        int c=a+b;
        int q=0;
        x=Integer.toString(c);
        q++;
        try{
                
                  conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data","root","");
                  String query="UPDATE `user_info` SET `WalBal`="+x+" WHERE Username='"+n+"'";
                st = conn.prepareStatement(query); 
                 st.execute();
                  balance.setText(x);
                  currbalance.setText(x);
                   walbalfinal=Integer.parseInt(x);
                JOptionPane.showMessageDialog(null,"Money Added");
                this.dispose();
                 Proifile1 pf2=new Proifile1();
                 pf2.pack();
                 pf2.setVisible(true);
                  pf2.setLocationRelativeTo(null);
        }
         catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(null,"Error");
        }
    
        
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new Proifile1().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void currbalancePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_currbalancePropertyChange

    }//GEN-LAST:event_currbalancePropertyChange

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed

    }//GEN-LAST:event_jButton2KeyPressed

    private void toaddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toaddKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
        x=currbalance.getText();
        String y=toadd.getText();
        if(y.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please add amount");
        }
        int a=Integer.parseInt(x);
        int b=Integer.parseInt(y);
        int c=a+b;
        int q=0;
        x=Integer.toString(c);
        q++;
        try{
                
                  conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer_data","root","");
                  String query="UPDATE `user_info` SET `WalBal`="+x+" WHERE Username='"+n+"'";
                st = conn.prepareStatement(query); 
                 st.execute();
                  balance.setText(x);
                  currbalance.setText(x);
                   walbalfinal=Integer.parseInt(x);
                JOptionPane.showMessageDialog(null,"Money Added");
                this.dispose();
                 Proifile1 pf2=new Proifile1();
                 pf2.pack();
                 pf2.setVisible(true);
                  pf2.setLocationRelativeTo(null);
        }
         catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(null,"Error");
        }        // TODO add your handling code here:
}
    }//GEN-LAST:event_toaddKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wallet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wallet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wallet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wallet1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Wallet1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    public static javax.swing.JLabel currbalance;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField toadd;
    private javax.swing.JPanel walletpanel;
    // End of variables declaration//GEN-END:variables
}
